workflows:
  android-apk:
    name: Android APK
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      flutter: stable
      vars:
        API_BASE_URL: https://freitora.online/api/mobile
    scripts:
      - name: Generate Android project files
        script: |
          flutter create --platforms=android .
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Analyze project
        script: |
          flutter analyze
      - name: Build APK
        script: |
          flutter build apk --release --dart-define=API_BASE_URL=$API_BASE_URL
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
